// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdRUJkqq8nHG18HHdse1Tw-86DJHeJ-8E',
    appId: '1:800286997607:web:742d969e30f935ff81a8c2',
    messagingSenderId: '800286997607',
    projectId: 'furniture-d157a',
    authDomain: 'furniture-d157a.firebaseapp.com',
    storageBucket: 'furniture-d157a.appspot.com',
    measurementId: 'G-82M5NL75YE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiwE-6i3JDjL3G6Hq13AUOGGwi1P_0axI',
    appId: '1:800286997607:android:d1cdd07c5790a54d81a8c2',
    messagingSenderId: '800286997607',
    projectId: 'furniture-d157a',
    storageBucket: 'furniture-d157a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqWWJc3sdK5P0GfA9KovtCcchAwyJPemI',
    appId: '1:800286997607:ios:4be4b555136478bd81a8c2',
    messagingSenderId: '800286997607',
    projectId: 'furniture-d157a',
    storageBucket: 'furniture-d157a.appspot.com',
    iosClientId: '800286997607-4crhqk99dl9hhghjdhok6ig395v7e2jh.apps.googleusercontent.com',
    iosBundleId: 'com.example.furniture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqWWJc3sdK5P0GfA9KovtCcchAwyJPemI',
    appId: '1:800286997607:ios:4be4b555136478bd81a8c2',
    messagingSenderId: '800286997607',
    projectId: 'furniture-d157a',
    storageBucket: 'furniture-d157a.appspot.com',
    iosClientId: '800286997607-4crhqk99dl9hhghjdhok6ig395v7e2jh.apps.googleusercontent.com',
    iosBundleId: 'com.example.furniture',
  );
}
